//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JsonModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChallengeDayExersice
    {
        public int ID { get; set; }
        public int DayID { get; set; }
        public int ChallengeID { get; set; }
        public int ExersiceID { get; set; }
        public int Repeats { get; set; }
        public int RepeatType { get; set; }
        public int RepeatCircuit { get; set; }
    
        public virtual Challenge Challenge { get; set; }
        public virtual Exercise Exercise { get; set; }
        public virtual RepeatType RepeatType1 { get; set; }
    }
}
